In [66]:
import pandas as pd
import numpy as np

In [67]:
df = pd.read_csv('google_playstore_2026.csv')

In [68]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,In-App Purchases,Ad Supported
0,Strike Plus,FAMILY,4.6,12460594,Varies with device,"500,000,000+",Free,0.00,Teen,Family,"January 15, 2026",Varies with device,8.0 and up,Yes,Yes
1,Tracker AI,EDUCATION,3.4,11487705,Varies with device,"500,000,000+",Free,0.00,Everyone,Education,"October 22, 2025",Varies with device,11.0 and up,Yes,Yes
2,Scanner,FAMILY,3.5,10503932,Varies with device,"500,000,000+",Paid,0.99,Everyone,Family,"November 08, 2024",Varies with device,10.0 and up,No,No
3,Connect 3D,ART_AND_DESIGN,4.7,4818860,221.6M,"100,000,000+",Free,0.00,Everyone,Art And Design,"October 07, 2025",6.8.21,10.0 and up,No,Yes
4,VPN,PRODUCTIVITY,3.5,3562800,122.9M,"100,000,000+",Free,0.00,Everyone,Productivity,"June 29, 2026",5.5.11,12.0 and up,Yes,Yes

In [69]:
df = df[['App', 'Category', 'Size', 'Last Updated']]

In [70]:
df.sample()

              App Category     Size  Last Updated
1308  Strike Plus     GAME  1630.6M  May 12, 2024

In [71]:
df['Last Updated'] = pd.to_datetime(df['Last Updated'])

In [72]:
df.sample()

          App      Category                Size Last Updated
8824  Browser  PRODUCTIVITY  Varies with device   2025-07-26

In [73]:
df['Update Year'] = df['Last Updated'].dt.year
df.head()

           App        Category                Size Last Updated  Update Year
0  Strike Plus          FAMILY  Varies with device   2026-01-15         2026
1   Tracker AI       EDUCATION  Varies with device   2025-10-22         2025
2      Scanner          FAMILY  Varies with device   2024-11-08         2024
3   Connect 3D  ART_AND_DESIGN              221.6M   2025-10-07         2025
4          VPN    PRODUCTIVITY              122.9M   2026-06-29         2026

In [74]:
df['Update Month'] = df['Last Updated'].dt.month
df.head()

,App,Category,Size,Last Updated,Update Year,Update Month
0,Strike Plus,FAMILY,Varies with device,2026-01-15,2026,1
1,Tracker AI,EDUCATION,Varies with device,2025-10-22,2025,10
2,Scanner,FAMILY,Varies with device,2024-11-08,2024,11
3,Connect 3D,ART_AND_DESIGN,221.6M,2025-10-07,2025,10
4,VPN,PRODUCTIVITY,122.9M,2026-06-29,2026,6

In [75]:
df['Update Month'] = df['Last Updated'].dt.month_name()
df.head()

,App,Category,Size,Last Updated,Update Year,Update Month
0,Strike Plus,FAMILY,Varies with device,2026-01-15,2026,January
1,Tracker AI,EDUCATION,Varies with device,2025-10-22,2025,October
2,Scanner,FAMILY,Varies with device,2024-11-08,2024,November
3,Connect 3D,ART_AND_DESIGN,221.6M,2025-10-07,2025,October
4,VPN,PRODUCTIVITY,122.9M,2026-06-29,2026,June

In [76]:
df['Update Date'] = df['Last Updated'].dt.day
df.head()

,App,Category,Size,Last Updated,Update Year,Update Month,Update Date
0,Strike Plus,FAMILY,Varies with device,2026-01-15,2026,January,15
1,Tracker AI,EDUCATION,Varies with device,2025-10-22,2025,October,22
2,Scanner,FAMILY,Varies with device,2024-11-08,2024,November,8
3,Connect 3D,ART_AND_DESIGN,221.6M,2025-10-07,2025,October,7
4,VPN,PRODUCTIVITY,122.9M,2026-06-29,2026,June,29

In [77]:
df['Update Day of week'] = df['Last Updated'].dt.dayofweek
df.head()

,App,Category,Size,Last Updated,Update Year,Update Month,Update Date,Update Day of week
0,Strike Plus,FAMILY,Varies with device,2026-01-15,2026,January,15,3
1,Tracker AI,EDUCATION,Varies with device,2025-10-22,2025,October,22,2
2,Scanner,FAMILY,Varies with device,2024-11-08,2024,November,8,4
3,Connect 3D,ART_AND_DESIGN,221.6M,2025-10-07,2025,October,7,1
4,VPN,PRODUCTIVITY,122.9M,2026-06-29,2026,June,29,0

In [78]:
df['Update Day'] = df['Last Updated'].dt.day_name()
df.head()

,App,Category,Size,Last Updated,Update Year,Update Month,Update Date,Update Day of week,Update Day
0,Strike Plus,FAMILY,Varies with device,2026-01-15,2026,January,15,3,Thursday
1,Tracker AI,EDUCATION,Varies with device,2025-10-22,2025,October,22,2,Wednesday
2,Scanner,FAMILY,Varies with device,2024-11-08,2024,November,8,4,Friday
3,Connect 3D,ART_AND_DESIGN,221.6M,2025-10-07,2025,October,7,1,Tuesday
4,VPN,PRODUCTIVITY,122.9M,2026-06-29,2026,June,29,0,Monday

In [79]:
df['Update date_is_weekend'] = np.where(df['Update Day'].isin(['Sunday', 'Saturday']), "weekend","weekday")
df.head()

,App,Category,Size,Last Updated,Update Year,Update Month,Update Date,Update Day of week,Update Day,Update date_is_weekend
0,Strike Plus,FAMILY,Varies with device,2026-01-15,2026,January,15,3,Thursday,weekday
1,Tracker AI,EDUCATION,Varies with device,2025-10-22,2025,October,22,2,Wednesday,weekday
2,Scanner,FAMILY,Varies with device,2024-11-08,2024,November,8,4,Friday,weekday
3,Connect 3D,ART_AND_DESIGN,221.6M,2025-10-07,2025,October,7,1,Tuesday,weekday
4,VPN,PRODUCTIVITY,122.9M,2026-06-29,2026,June,29,0,Monday,weekday

In [80]:
df.sample(5)

,App,Category,Size,Last Updated,Update Year,Update Month,Update Date,Update Day of week,Update Day,Update date_is_weekend
167,Drive,TOOLS,102.6M,2026-03-30,2026,March,30,0,Monday,weekday
9847,Epic Tracker Premium,GAME,936.9M,2024-01-30,2024,January,30,1,Tuesday,weekday
10208,Drive,TOOLS,82.2M,2026-06-14,2026,June,14,6,Sunday,weekend
1300,Hyper Player,GAME,Varies with device,2025-08-15,2025,August,15,4,Friday,weekday
9283,Strike Hub,FAMILY,42.4M,2026-04-19,2026,April,19,6,Sunday,weekend

In [83]:
df['week of the year'] = df['Last Updated'].dt.isocalendar().week
df.head()

,App,Category,Size,Last Updated,Update Year,Update Month,Update Date,Update Day of week,Update Day,Update date_is_weekend,week of the year
0,Strike Plus,FAMILY,Varies with device,2026-01-15,2026,January,15,3,Thursday,weekday,3
1,Tracker AI,EDUCATION,Varies with device,2025-10-22,2025,October,22,2,Wednesday,weekday,43
2,Scanner,FAMILY,Varies with device,2024-11-08,2024,November,8,4,Friday,weekday,45
3,Connect 3D,ART_AND_DESIGN,221.6M,2025-10-07,2025,October,7,1,Tuesday,weekday,41
4,VPN,PRODUCTIVITY,122.9M,2026-06-29,2026,June,29,0,Monday,weekday,27

In [85]:
df['quarter of year'] = df['Last Updated'].dt.quarter
df.head()

,App,Category,Size,Last Updated,Update Year,Update Month,Update Date,Update Day of week,Update Day,Update date_is_weekend,week of the year,quarter of year
0,Strike Plus,FAMILY,Varies with device,2026-01-15,2026,January,15,3,Thursday,weekday,3,1
1,Tracker AI,EDUCATION,Varies with device,2025-10-22,2025,October,22,2,Wednesday,weekday,43,4
2,Scanner,FAMILY,Varies with device,2024-11-08,2024,November,8,4,Friday,weekday,45,4
3,Connect 3D,ART_AND_DESIGN,221.6M,2025-10-07,2025,October,7,1,Tuesday,weekday,41,4
4,VPN,PRODUCTIVITY,122.9M,2026-06-29,2026,June,29,0,Monday,weekday,27,2

In [89]:
df['semester'] = np.where(df['quarter of year'].isin([1,2]), 1, 2)
df.head()

,App,Category,Size,Last Updated,Update Year,Update Month,Update Date,Update Day of week,Update Day,Update date_is_weekend,week of the year,quarter of year,semester
0,Strike Plus,FAMILY,Varies with device,2026-01-15,2026,January,15,3,Thursday,weekday,3,1,1
1,Tracker AI,EDUCATION,Varies with device,2025-10-22,2025,October,22,2,Wednesday,weekday,43,4,2
2,Scanner,FAMILY,Varies with device,2024-11-08,2024,November,8,4,Friday,weekday,45,4,2
3,Connect 3D,ART_AND_DESIGN,221.6M,2025-10-07,2025,October,7,1,Tuesday,weekday,41,4,2
4,VPN,PRODUCTIVITY,122.9M,2026-06-29,2026,June,29,0,Monday,weekday,27,2,1

# Elapsed time

In [90]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 7, 17, 12, 9, 22, 837464)

In [91]:
today - df['Last Updated']

0       183 days 12:09:22.837464
1       268 days 12:09:22.837464
2       616 days 12:09:22.837464
3       283 days 12:09:22.837464
4        18 days 12:09:22.837464
                  ...
11495   700 days 12:09:22.837464
11496   675 days 12:09:22.837464
11497   246 days 12:09:22.837464
11498   260 days 12:09:22.837464
11499   228 days 12:09:22.837464
Name: Last Updated, Length: 11500, dtype: timedelta64[ns]

In [99]:
(today - df['Last Updated']).dt.days

0        183
1        268
2        616
3        283
4         18
        ...
11495    700
11496    675
11497    246
11498    260
11499    228
Name: Last Updated, Length: 11500, dtype: int64

In [104]:
# Months passed
# 1. Calculate the difference in days using np.timedelta64(1, 'D')
days_passed = (today - df['Last Updated']) / np.timedelta64(1, 'D')

# 2. Divide by 30.44 (average days per month) and round it
df['Months Passed'] = np.round(days_passed / 30.44, 0)

In [105]:
df.head()

,App,Category,Size,Last Updated,Update Year,Update Month,Update Date,Update Day of week,Update Day,Update date_is_weekend,week of the year,quarter of year,semester,Months Passed
0,Strike Plus,FAMILY,Varies with device,2026-01-15,2026,January,15,3,Thursday,weekday,3,1,1,6.0
1,Tracker AI,EDUCATION,Varies with device,2025-10-22,2025,October,22,2,Wednesday,weekday,43,4,2,9.0
2,Scanner,FAMILY,Varies with device,2024-11-08,2024,November,8,4,Friday,weekday,45,4,2,20.0
3,Connect 3D,ART_AND_DESIGN,221.6M,2025-10-07,2025,October,7,1,Tuesday,weekday,41,4,2,9.0
4,VPN,PRODUCTIVITY,122.9M,2026-06-29,2026,June,29,0,Monday,weekday,27,2,1,1.0