In [1]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('netflix_titles.csv')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [19]:
df.sample()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
171,s172,Movie,Same Kind of Different as Me,Michael Carney,"Greg Kinnear, Renée Zellweger, Djimon Hounsou,...",United States,"September 1, 2021",2017,PG-13,120 min,"Dramas, Faith & Spirituality",A wealthy couple whose marriage is on the rock...

In [15]:
df['duration'].value_counts()

duration
1 Season     1793
2 Seasons     425
3 Seasons     199
90 min        152
94 min        146
             ...
16 min          1
186 min         1
193 min         1
189 min         1
191 min         1
Name: count, Length: 220, dtype: int64

In [20]:
df = df[['type','title','date_added', 'duration']]

In [21]:
df.sample()

       type title     date_added duration
6654  Movie   Dum  March 1, 2018  162 min

In [47]:
df["duration"].str.extract('(\D+)')

             0
0          min
1      Seasons
2       Season
3       Season
4      Seasons
...        ...
8802       min
8803   Seasons
8804       min
8805       min
8806       min

[8807 rows x 1 columns]

In [73]:
np.where(df["duration"].str.contains('Season',na=False), df["duration"].str.extract('(\d+)').astype('float'), np.nan)

array([[ nan,  90.,  90., ...,  nan,  nan,  nan],
       [ nan,   2.,   2., ...,  nan,  nan,  nan],
       [ nan,   1.,   1., ...,  nan,  nan,  nan],
       ...,
       [ nan,  88.,  88., ...,  nan,  nan,  nan],
       [ nan,  88.,  88., ...,  nan,  nan,  nan],
       [ nan, 111., 111., ...,  nan,  nan,  nan]], shape=(8807, 8807))

In [57]:
df

         type                  title          date_added   duration
0       Movie   Dick Johnson Is Dead  September 25, 2021     90 min
1     TV Show          Blood & Water  September 24, 2021  2 Seasons
2     TV Show              Ganglands  September 24, 2021   1 Season
3     TV Show  Jailbirds New Orleans  September 24, 2021   1 Season
4     TV Show           Kota Factory  September 24, 2021  2 Seasons
...       ...                    ...                 ...        ...
8802    Movie                 Zodiac   November 20, 2019    158 min
8803  TV Show            Zombie Dumb        July 1, 2019  2 Seasons
8804    Movie             Zombieland    November 1, 2019     88 min
8805    Movie                   Zoom    January 11, 2020     88 min
8806    Movie                 Zubaan       March 2, 2019    111 min

[8807 rows x 4 columns]

In [76]:
df.loc[df['duration'].str.contains('Season', na=False), 'duration'].str.extract('(\d+)').astype(float)

        0
1     2.0
2     1.0
3     1.0
4     2.0
5     1.0
...   ...
8795  2.0
8796  2.0
8797  3.0
8800  1.0
8803  2.0

[2676 rows x 1 columns]

In [78]:
df['seasons'] = df.loc[df['duration'].str.contains('Season', na=False), 'duration'].str.extract('(\d+)').astype(float)

In [79]:
df

         type                  title          date_added   duration  seasons
0       Movie   Dick Johnson Is Dead  September 25, 2021     90 min      NaN
1     TV Show          Blood & Water  September 24, 2021  2 Seasons      2.0
2     TV Show              Ganglands  September 24, 2021   1 Season      1.0
3     TV Show  Jailbirds New Orleans  September 24, 2021   1 Season      1.0
4     TV Show           Kota Factory  September 24, 2021  2 Seasons      2.0
...       ...                    ...                 ...        ...      ...
8802    Movie                 Zodiac   November 20, 2019    158 min      NaN
8803  TV Show            Zombie Dumb        July 1, 2019  2 Seasons      2.0
8804    Movie             Zombieland    November 1, 2019     88 min      NaN
8805    Movie                   Zoom    January 11, 2020     88 min      NaN
8806    Movie                 Zubaan       March 2, 2019    111 min      NaN

[8807 rows x 5 columns]

In [80]:
df.loc[df['duration'].str.contains('min', na=False), 'duration'].str.extract('(\d+)').astype(float)

          0
0      90.0
6      91.0
7     125.0
9     104.0
12    127.0
...     ...
8801   96.0
8802  158.0
8804   88.0
8805   88.0
8806  111.0

[6128 rows x 1 columns]

In [81]:
df['Movies_runtime'] = df.loc[df['duration'].str.contains('min', na=False), 'duration'].str.extract('(\d+)').astype(float)

In [82]:
df

,type,title,date_added,duration,seasons,Movies_runtime
0,Movie,Dick Johnson Is Dead,"September 25, 2021",90 min,NaN,90.0
1,TV Show,Blood & Water,"September 24, 2021",2 Seasons,2.0,NaN
2,TV Show,Ganglands,"September 24, 2021",1 Season,1.0,NaN
3,TV Show,Jailbirds New Orleans,"September 24, 2021",1 Season,1.0,NaN
4,TV Show,Kota Factory,"September 24, 2021",2 Seasons,2.0,NaN
...,...,...,...,...,...,...
8802,Movie,Zodiac,"November 20, 2019",158 min,NaN,158.0
8803,TV Show,Zombie Dumb,"July 1, 2019",2 Seasons,2.0,NaN
8804,Movie,Zombieland,"November 1, 2019",88 min,NaN,88.0
8805,Movie,Zoom,"January 11, 2020",88 min,NaN,88.0
8806,Movie,Zubaan,"March 2, 2019",111 min,NaN,111.0